name: Run CI
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - '*'
jobs:
  ci-n8n:
    uses: ./.github/workflows/ci-n8n.yaml
    secrets: inherit
